DROP TABLE IF EXISTS investment_data_quality_snapshot;
DROP TABLE IF EXISTS investment_data_job;
DROP TABLE IF EXISTS quant_validation_report;
DROP TABLE IF EXISTS quant_experiment;
DROP TABLE IF EXISTS quant_universe_membership;
DROP TABLE IF EXISTS quant_research_universe;
DROP TABLE IF EXISTS benchmark_profile;
DROP TABLE IF EXISTS quant_paper_fill;
DROP TABLE IF EXISTS quant_paper_order;
DROP TABLE IF EXISTS quant_model_monitor;
DROP TABLE IF EXISTS quant_backtest_run;
DROP TABLE IF EXISTS quant_prediction;
DROP TABLE IF EXISTS quant_strategy_version;
DROP TABLE IF EXISTS quant_model_version;
DROP TABLE IF EXISTS quant_training_run;
DROP TABLE IF EXISTS quant_job;
DROP TABLE IF EXISTS quant_feature_set;
DROP TABLE IF EXISTS investment_horizon_setting;
DROP TABLE IF EXISTS investment_horizon_profile;
DROP TABLE IF EXISTS investment_analysis_snapshot;
DROP TABLE IF EXISTS investment_analysis_preference;
DROP TABLE IF EXISTS wealth_baseline;
DROP TABLE IF EXISTS investment_asset;
DROP TABLE IF EXISTS daily_exchange_rate;
DROP TABLE IF EXISTS investment_plan;
DROP TABLE IF EXISTS investment_sync_batch;
DROP TABLE IF EXISTS investment_import_batch;
DROP TABLE IF EXISTS product_daily_quote;
DROP TABLE IF EXISTS investment_position;
DROP TABLE IF EXISTS investment_cash_ledger;
DROP TABLE IF EXISTS investment_cash_balance;
DROP TABLE IF EXISTS investment_transaction;
DROP TABLE IF EXISTS investment_account;
DROP TABLE IF EXISTS investment_product;
DROP TABLE IF EXISTS expense_category;
DROP TABLE IF EXISTS chat_message;
DROP TABLE IF EXISTS pending_action;
DROP TABLE IF EXISTS agent_schedule_run;
DROP TABLE IF EXISTS agent_schedule;
DROP TABLE IF EXISTS agent_reflection;
DROP TABLE IF EXISTS agent_run_step;
DROP TABLE IF EXISTS agent_run;
DROP TABLE IF EXISTS skill_invocation_record;
DROP TABLE IF EXISTS agent_skill;
DROP TABLE IF EXISTS agent_memory;
DROP TABLE IF EXISTS bill_candidate_transaction;
DROP TABLE IF EXISTS bill_import_record;
DROP TABLE IF EXISTS transaction;
DROP TABLE IF EXISTS financial_profile;
DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    nickname   VARCHAR(50),
    email      VARCHAR(100),
    avatar     VARCHAR(255),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted    TINYINT      NOT NULL DEFAULT 0
);

CREATE TABLE financial_profile
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT        NOT NULL UNIQUE,
    life_stage            VARCHAR(50),
    monthly_income        DECIMAL(12,2) NOT NULL DEFAULT 0,
    fixed_expense         DECIMAL(12,2) NOT NULL DEFAULT 0,
    risk_preference       VARCHAR(30),
    savings_goal_amount   DECIMAL(12,2) NOT NULL DEFAULT 0,
    savings_goal_deadline VARCHAR(7),
    monthly_budget_goal   DECIMAL(12,2) NOT NULL DEFAULT 0,
    notes                 VARCHAR(500),
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_financial_profile_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE agent_memory
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    memory_type  VARCHAR(50)  NOT NULL,
    memory_key   VARCHAR(100) NOT NULL,
    memory_value CLOB NOT NULL,
    confidence   DOUBLE       NOT NULL DEFAULT 1,
    source_query VARCHAR(500),
    disabled     TINYINT      NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      TINYINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_agent_memory_key UNIQUE (user_id, memory_type, memory_key),
    CONSTRAINT fk_agent_memory_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE agent_skill
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    skill_key        VARCHAR(120) NOT NULL,
    name             VARCHAR(120) NOT NULL,
    description      VARCHAR(500),
    version          VARCHAR(50),
    author           VARCHAR(120),
    category         VARCHAR(80),
    risk_level       VARCHAR(50),
    input_schema     VARCHAR(500),
    trigger_text     VARCHAR(500),
    instruction_text CLOB,
    bound_tools      VARCHAR(500),
    source_type      VARCHAR(50)  NOT NULL,
    source_uri       VARCHAR(500) NOT NULL,
    source_version   VARCHAR(100),
    enabled          TINYINT      NOT NULL DEFAULT 1,
    built_in         TINYINT      NOT NULL DEFAULT 0,
    deleted          TINYINT      NOT NULL DEFAULT 0,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_skill_source UNIQUE (user_id, source_type, source_uri, skill_key),
    CONSTRAINT fk_agent_skill_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE skill_invocation_record
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    trace_id   VARCHAR(64),
    skill_name VARCHAR(100) NOT NULL,
    category   VARCHAR(50),
    source_type VARCHAR(50),
    risk_level VARCHAR(50),
    input      TEXT,
    success    TINYINT      NOT NULL DEFAULT 0,
    blocked    TINYINT      NOT NULL DEFAULT 0,
    duration_ms BIGINT,
    summary    VARCHAR(500),
    raw_result TEXT,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_skill_invocation_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);


CREATE TABLE agent_run
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    trace_id      VARCHAR(64) NOT NULL UNIQUE,
    query         TEXT        NOT NULL,
    final_answer  TEXT,
    status        VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
    started_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at   TIMESTAMP,
    duration_ms   BIGINT,
    error_message VARCHAR(500),
    CONSTRAINT fk_agent_run_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE agent_run_step
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT      NOT NULL,
    trace_id            VARCHAR(64) NOT NULL,
    step_number         INT         NOT NULL,
    summary             VARCHAR(500),
    tool_name           VARCHAR(100),
    input               TEXT,
    success             TINYINT,
    observation_summary VARCHAR(500),
    error_message       VARCHAR(500),
    status              VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
    started_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at         TIMESTAMP,
    CONSTRAINT uk_agent_run_step UNIQUE (trace_id, step_number),
    CONSTRAINT fk_agent_run_step_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE agent_reflection
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    trace_id        VARCHAR(64)  NOT NULL,
    suggestion_type VARCHAR(50)  NOT NULL,
    title           VARCHAR(120) NOT NULL,
    summary         VARCHAR(500) NOT NULL,
    payload         TEXT,
    status          VARCHAR(30)  NOT NULL DEFAULT 'OPEN',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_agent_reflection_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);
CREATE TABLE transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL,
    amount           DECIMAL(12,2) NOT NULL,
    type             VARCHAR(10)   NOT NULL DEFAULT 'EXPENSE',
    category         VARCHAR(50)   NOT NULL,
    description      VARCHAR(500),
    transaction_date DATE          NOT NULL,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          TINYINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_transaction_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE expense_category
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL DEFAULT 0,
    name            VARCHAR(50)  NOT NULL,
    icon            VARCHAR(50),
    benchmark_min   INT,
    benchmark_max   INT,
    benchmark_label VARCHAR(100),
    sort_order      INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_user_category UNIQUE (user_id, name)
);

CREATE TABLE chat_message
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    role       VARCHAR(20) NOT NULL,
    content    TEXT        NOT NULL,
    trace_id   VARCHAR(64),
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE pending_action
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    action_type VARCHAR(50)  NOT NULL,
    title       VARCHAR(100) NOT NULL,
    summary     VARCHAR(500) NOT NULL,
    payload     TEXT         NOT NULL,
    status      VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pending_action_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE agent_schedule
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    trace_id        VARCHAR(64),
    name            VARCHAR(200) NOT NULL,
    description     VARCHAR(500),
    cron_expression VARCHAR(100) NOT NULL,
    timezone        VARCHAR(50)  NOT NULL DEFAULT 'Asia/Shanghai',
    task_query      TEXT         NOT NULL,
    enabled         TINYINT      NOT NULL DEFAULT 1,
    last_run_at     TIMESTAMP,
    next_run_at     TIMESTAMP,
    lock_until      TIMESTAMP,
    run_count       INT          NOT NULL DEFAULT 0,
    consecutive_failures INT     NOT NULL DEFAULT 0,
    last_status     VARCHAR(20),
    last_answer     TEXT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_agent_schedule_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE agent_schedule_run
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id   BIGINT      NOT NULL,
    user_id       BIGINT      NOT NULL,
    trace_id      VARCHAR(64),
    status        VARCHAR(20) NOT NULL,
    answer        TEXT,
    error_message TEXT,
    started_at    TIMESTAMP   NOT NULL,
    finished_at   TIMESTAMP   NOT NULL,
    duration_ms   BIGINT      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_schedule_run_schedule FOREIGN KEY (schedule_id) REFERENCES agent_schedule (id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_schedule_run_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE bill_import_record
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    original_filename VARCHAR(255),
    file_path         VARCHAR(500) NOT NULL,
    bill_type         VARCHAR(50)  NOT NULL DEFAULT 'UNKNOWN',
    confidence        DECIMAL(5,4) NOT NULL DEFAULT 0,
    ocr_text          TEXT,
    warnings          TEXT,
    status            VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           TINYINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_bill_import_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE bill_candidate_transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_import_id   BIGINT        NOT NULL,
    user_id          BIGINT        NOT NULL,
    amount           DECIMAL(12,2) NOT NULL,
    type             VARCHAR(10)   NOT NULL DEFAULT 'EXPENSE',
    category         VARCHAR(50)   NOT NULL DEFAULT '其他',
    description      VARCHAR(500),
    transaction_date DATE          NOT NULL,
    confidence       DECIMAL(5,4)  NOT NULL DEFAULT 0,
    status           VARCHAR(30)   NOT NULL DEFAULT 'PENDING',
    transaction_id   BIGINT,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          TINYINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_candidate_bill FOREIGN KEY (bill_import_id) REFERENCES bill_import_record (id) ON DELETE CASCADE,
    CONSTRAINT fk_candidate_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE investment_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type VARCHAR(30) NOT NULL,
    market VARCHAR(30) NOT NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(160) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'CNY',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    inception_date DATE,
    history_start_date DATE,
    history_end_date DATE,
    history_coverage_complete BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_investment_product UNIQUE(product_type, market, code)
);

CREATE TABLE investment_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_name VARCHAR(120) NOT NULL,
    account_type VARCHAR(30) NOT NULL,
    base_currency VARCHAR(3) NOT NULL DEFAULT 'CNY',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE investment_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    product_id BIGINT,
    event_type VARCHAR(30) NOT NULL,
    trade_date DATE NOT NULL,
    settlement_date DATE,
    currency VARCHAR(3) NOT NULL,
    quantity DECIMAL(28,10),
    price DECIMAL(28,10),
    amount DECIMAL(28,8),
    fee DECIMAL(28,8) NOT NULL DEFAULT 0,
    factor DECIMAL(28,10),
    source VARCHAR(30) NOT NULL DEFAULT 'MANUAL',
    external_ref VARCHAR(120),
    reversal_transaction_id BIGINT,
    note VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_investment_transaction_ref UNIQUE(user_id, source, external_ref)
);

CREATE TABLE investment_cash_balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    balance DECIMAL(28,8) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_investment_cash_balance UNIQUE(account_id, currency)
);

CREATE TABLE investment_cash_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    transaction_id BIGINT NOT NULL UNIQUE,
    currency VARCHAR(3) NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    amount DECIMAL(28,8) NOT NULL,
    external_flow TINYINT NOT NULL DEFAULT 0,
    occurred_on DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE investment_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity DECIMAL(28,10) NOT NULL DEFAULT 0,
    cost_amount DECIMAL(28,8) NOT NULL DEFAULT 0,
    average_cost DECIMAL(28,10) NOT NULL DEFAULT 0,
    realized_pnl DECIMAL(28,8) NOT NULL DEFAULT 0,
    latest_price DECIMAL(28,10),
    market_value_cny DECIMAL(28,8),
    unrealized_pnl_cny DECIMAL(28,8),
    data_date DATE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_investment_position UNIQUE(account_id, product_id)
);

CREATE TABLE product_daily_quote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    open_price DECIMAL(28,10),
    high_price DECIMAL(28,10),
    low_price DECIMAL(28,10),
    close_price DECIMAL(28,10) NOT NULL,
    previous_close DECIMAL(28,10),
    change_amount DECIMAL(28,10),
    change_percent DECIMAL(18,8),
    volume DECIMAL(28,8),
    amount DECIMAL(28,8),
    turnover_rate DECIMAL(18,8),
    volume_ratio DECIMAL(18,8),
    amplitude DECIMAL(18,8),
    adjust_type VARCHAR(20) NOT NULL DEFAULT 'NONE',
    source VARCHAR(40) NOT NULL,
    adapter_version VARCHAR(40),
    synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_product_daily_quote UNIQUE(product_id, trade_date, adjust_type)
);

CREATE TABLE investment_import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,
    payload CLOB NOT NULL,
    row_count INT NOT NULL DEFAULT 0,
    error_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE investment_sync_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    job_type VARCHAR(40) NOT NULL,
    provider VARCHAR(40),
    status VARCHAR(30) NOT NULL,
    rows_success INT NOT NULL DEFAULT 0,
    rows_failed INT NOT NULL DEFAULT 0,
    error_message VARCHAR(500),
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP
);

CREATE TABLE investment_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    amount DECIMAL(28,8) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    frequency VARCHAR(20) NOT NULL,
    execution_day INT NOT NULL,
    next_execution_date DATE NOT NULL,
    last_execution_date DATE,
    last_execution_amount DECIMAL(28,8),
    last_execution_price DECIMAL(28,10),
    execution_count INT NOT NULL DEFAULT 0,
    last_execution_status VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    last_execution_message VARCHAR(500),
    enabled TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE daily_exchange_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency VARCHAR(3) NOT NULL,
    quote_currency VARCHAR(3) NOT NULL,
    rate_date DATE NOT NULL,
    rate DECIMAL(28,10) NOT NULL,
    source VARCHAR(40) NOT NULL,
    adapter_version VARCHAR(40),
    synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_daily_exchange_rate UNIQUE(base_currency, quote_currency, rate_date)
);

CREATE TABLE investment_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity DECIMAL(28,10),
    average_cost DECIMAL(28,10),
    note VARCHAR(500),
    current_transaction_id BIGINT,
    sync_status VARCHAR(30) NOT NULL DEFAULT 'NOT_SYNCED',
    sync_error VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE investment_data_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    job_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    force_refresh BOOLEAN NOT NULL DEFAULT FALSE,
    record_count INT NOT NULL DEFAULT 0,
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP,
    lease_until TIMESTAMP,
    lease_token VARCHAR(36),
    error_message VARCHAR(1000),
    requested_start_date DATE,
    sample_start_date DATE,
    sample_end_date DATE,
    coverage_complete BOOLEAN,
    dataset_version VARCHAR(128),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_investment_data_job_asset_type UNIQUE(asset_id, job_type)
);

CREATE INDEX idx_investment_data_job_pending
    ON investment_data_job(status, next_retry_at, created_at);

CREATE TABLE wealth_baseline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    entered_total_assets DECIMAL(28,8) NOT NULL,
    baseline_non_investment_balance DECIMAL(28,8) NOT NULL,
    baseline_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE investment_analysis_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    short_min_days INT NOT NULL DEFAULT 5,
    short_max_days INT NOT NULL DEFAULT 20,
    medium_min_days INT NOT NULL DEFAULT 20,
    medium_max_days INT NOT NULL DEFAULT 120,
    long_min_days INT NOT NULL DEFAULT 120,
    long_max_days INT NOT NULL DEFAULT 500,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_analysis_preference_user_asset UNIQUE(user_id, asset_id)
);

CREATE TABLE investment_horizon_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scope_type VARCHAR(16) NOT NULL,
    asset_id BIGINT,
    version INT NOT NULL,
    template_version VARCHAR(64) NOT NULL,
    source VARCHAR(24) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_horizon_profile_resolution
    ON investment_horizon_profile(user_id, scope_type, asset_id, active, version);

CREATE TABLE investment_horizon_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    horizon_code VARCHAR(32) NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    sort_order INT NOT NULL,
    min_holding_days INT NOT NULL,
    max_holding_days INT NOT NULL,
    target_holding_days INT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_horizon_setting_profile_code UNIQUE(profile_id, horizon_code),
    CONSTRAINT fk_horizon_setting_profile FOREIGN KEY(profile_id)
        REFERENCES investment_horizon_profile(id)
);

CREATE INDEX idx_horizon_setting_profile
    ON investment_horizon_setting(profile_id, sort_order);

CREATE TABLE investment_analysis_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    rule_version VARCHAR(40) NOT NULL,
    preference_hash VARCHAR(64) NOT NULL,
    horizon_profile_version VARCHAR(255),
    horizon_config_json CLOB,
    signal_hash VARCHAR(64),
    quote_date DATE,
    technical_json CLOB,
    fundamental_json CLOB,
    fund_json CLOB,
    backtest_json CLOB,
    source_status_json CLOB,
    ai_explanation CLOB,
    analysis_status VARCHAR(30) NOT NULL DEFAULT 'READY',
    analyzed_at TIMESTAMP NOT NULL,
    ai_updated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_analysis_snapshot_user_asset_rule UNIQUE(user_id, asset_id, rule_version)
);

CREATE TABLE quant_feature_set (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_set_version VARCHAR(64) NOT NULL UNIQUE,
    quant_config_version VARCHAR(80) NOT NULL,
    product_type VARCHAR(30) NOT NULL,
    schema_json CLOB NOT NULL,
    artifact_uri VARCHAR(1000),
    artifact_hash VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE investment_data_quality_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_version VARCHAR(64) NOT NULL,
    product_type VARCHAR(30) NOT NULL,
    code VARCHAR(64) NOT NULL,
    market VARCHAR(30) NOT NULL,
    frequency VARCHAR(20) NOT NULL,
    adjust_type VARCHAR(20) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    adapter_version VARCHAR(80) NOT NULL,
    quality_config_version VARCHAR(80) NOT NULL,
    quality_rule_set_version VARCHAR(80) NOT NULL,
    quality_status VARCHAR(20) NOT NULL,
    decision VARCHAR(20) NOT NULL,
    enforcement_mode VARCHAR(20) NOT NULL,
    requested_start_date DATE NOT NULL,
    requested_end_date DATE NOT NULL,
    sample_start_date DATE NOT NULL,
    sample_end_date DATE NOT NULL,
    fetched_at TIMESTAMP NOT NULL,
    evaluated_at TIMESTAMP NOT NULL,
    manifest_json CLOB NOT NULL,
    report_json CLOB NOT NULL,
    secondary_dataset_versions_json CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_data_quality_version UNIQUE(dataset_version, quality_config_version)
);

CREATE TABLE quant_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, asset_id BIGINT, external_job_id VARCHAR(32) NOT NULL UNIQUE,
    job_type VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL,
    execution_status VARCHAR(20), training_outcome VARCHAR(24),
    deployment_status VARCHAR(24), economic_role VARCHAR(32),
    optimization_study_id VARCHAR(120), optimization_generation INT,
    baseline_comparison_json CLOB, diagnostics_json CLOB,
    experiment_fingerprint VARCHAR(64), request_fingerprint VARCHAR(64),
    error_code VARCHAR(40), error_summary VARCHAR(500),
    dataset_version VARCHAR(64),
    feature_set_version VARCHAR(64), quant_config_version VARCHAR(80),
    product_type VARCHAR(30), metrics_json CLOB,
    model_version VARCHAR(64), strategy_version VARCHAR(80),
    horizon_profile_version VARCHAR(255), horizon_code VARCHAR(32), horizon_days INT,
    result_json CLOB, user_message VARCHAR(500), started_at TIMESTAMP, finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_quant_job_fingerprint
    ON quant_job(user_id, experiment_fingerprint);
CREATE UNIQUE INDEX uk_quant_job_training_request
    ON quant_job(user_id, asset_id, job_type, request_fingerprint);

CREATE TABLE benchmark_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type VARCHAR(30) NOT NULL,
    product_code VARCHAR(40),
    model_family VARCHAR(40) NOT NULL,
    benchmark_code VARCHAR(40) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    composition_json CLOB NOT NULL,
    currency VARCHAR(10) NOT NULL,
    fx_rule VARCHAR(80),
    source_uri VARCHAR(1000) NOT NULL,
    source_version VARCHAR(120) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_benchmark_profile UNIQUE(product_type, product_code, effective_from)
);

CREATE TABLE quant_research_universe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    universe_code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    model_family VARCHAR(40) NOT NULL,
    market VARCHAR(30),
    selection_rule_json CLOB NOT NULL,
    dataset_version VARCHAR(64),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quant_universe_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    universe_id BIGINT NOT NULL,
    product_id BIGINT,
    product_type VARCHAR(30) NOT NULL,
    market VARCHAR(30),
    code VARCHAR(40) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE,
    source_snapshot VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_quant_universe_membership UNIQUE(universe_id, code, valid_from)
);

CREATE TABLE quant_experiment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    asset_id BIGINT,
    universe_id BIGINT,
    model_family VARCHAR(40) NOT NULL,
    horizon_code VARCHAR(32) NOT NULL,
    horizon_days INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    execution_status VARCHAR(20), training_outcome VARCHAR(24),
    deployment_status VARCHAR(24), economic_role VARCHAR(32),
    optimization_study_id VARCHAR(120), optimization_generation INT,
    baseline_comparison_json CLOB,
    training_mode VARCHAR(16) NOT NULL DEFAULT 'AUTO',
    trigger_reason VARCHAR(40) NOT NULL DEFAULT 'MIGRATION',
    parent_model_version VARCHAR(64),
    best_model_version VARCHAR(64),
    search_summary_json CLOB,
    experiment_fingerprint VARCHAR(64) NOT NULL,
    config_json CLOB NOT NULL,
    dataset_version VARCHAR(64),
    feature_set_version VARCHAR(64),
    quant_config_version VARCHAR(120) NOT NULL,
    code_version VARCHAR(120) NOT NULL,
    candidate_model_version VARCHAR(64),
    logs_json CLOB,
    error_code VARCHAR(40),
    error_summary VARCHAR(500),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_quant_experiment_fingerprint UNIQUE(user_id, experiment_fingerprint)
);

CREATE TABLE quant_validation_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_id BIGINT,
    model_version VARCHAR(64) NOT NULL UNIQUE,
    lifecycle VARCHAR(20) NOT NULL,
    passed BOOLEAN NOT NULL,
    failure_codes_json CLOB NOT NULL,
    checks_json CLOB NOT NULL,
    metrics_json CLOB NOT NULL,
    dataset_version VARCHAR(64),
    feature_set_version VARCHAR(64),
    quant_config_version VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quant_model_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_version VARCHAR(64) NOT NULL UNIQUE, feature_set_version VARCHAR(64) NOT NULL,
    quant_config_version VARCHAR(80) NOT NULL, product_type VARCHAR(30) NOT NULL,
    horizon_days INT NOT NULL, status VARCHAR(20) NOT NULL, artifact_uri VARCHAR(1000),
    deployment_status VARCHAR(24), economic_role VARCHAR(32),
    optimization_study_id VARCHAR(120), optimization_generation INT,
    baseline_comparison_json CLOB,
    artifact_hash VARCHAR(64) NOT NULL, metrics_json CLOB NOT NULL, trained_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quant_strategy_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_version VARCHAR(80) NOT NULL UNIQUE, model_version VARCHAR(64) NOT NULL,
    user_id BIGINT, asset_id BIGINT,
    product_type VARCHAR(30) NOT NULL, model_family VARCHAR(40), horizon_code VARCHAR(32),
    deployment_role VARCHAR(20) NOT NULL DEFAULT 'ARCHIVED', status VARCHAR(20) NOT NULL,
    validation_metrics_json CLOB NOT NULL, activated_at TIMESTAMP, retired_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quant_prediction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, asset_id BIGINT NOT NULL, dataset_version VARCHAR(64) NOT NULL,
    feature_set_version VARCHAR(64) NOT NULL, model_version VARCHAR(64), strategy_version VARCHAR(80),
    model_family VARCHAR(40),
    horizon_profile_version VARCHAR(255), horizon_code VARCHAR(32) NOT NULL, horizon_days INT NOT NULL,
    as_of_date DATE NOT NULL, profit_probability DECIMAL(18,10),
    loss_probability DECIMAL(18,10), expected_net_return DECIMAL(18,10),
    probability_positive_excess DECIMAL(18,10),
    expected_excess_return DECIMAL(18,10), interval_lower DECIMAL(18,10), interval_upper DECIMAL(18,10),
    confidence VARCHAR(16) NOT NULL, action VARCHAR(24) NOT NULL,
    target_weight DECIMAL(18,10) NOT NULL DEFAULT 0, market_regime VARCHAR(30), benchmark_code VARCHAR(40),
    round_trip_cost_bps DECIMAL(18,6),
    feature_vector_json CLOB, top_factors_json CLOB, risk_flags_json CLOB, backtest_summary_json CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quant_backtest_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_version VARCHAR(64), strategy_version VARCHAR(80), dataset_version VARCHAR(64) NOT NULL,
    horizon_days INT NOT NULL, status VARCHAR(20) NOT NULL, metrics_json CLOB NOT NULL,
    equity_curve_uri VARCHAR(1000), equity_curve_hash VARCHAR(64), started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quant_model_monitor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_version VARCHAR(64) NOT NULL, monitored_on DATE NOT NULL, brier_score DECIMAL(18,10),
    realized_excess_return DECIMAL(18,10), drawdown DECIMAL(18,10), drift_status VARCHAR(20) NOT NULL,
    evidence_json CLOB, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_quant_model_monitor_day UNIQUE(model_version, monitored_on)
);

CREATE TABLE quant_paper_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, account_id BIGINT NOT NULL, product_id BIGINT NOT NULL,
    strategy_version VARCHAR(80) NOT NULL, prediction_id BIGINT, side VARCHAR(10) NOT NULL,
    order_type VARCHAR(20) NOT NULL, quantity DECIMAL(28,10) NOT NULL,
    limit_price DECIMAL(28,10), status VARCHAR(20) NOT NULL, submitted_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quant_paper_fill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL, fill_date DATE NOT NULL, quantity DECIMAL(28,10) NOT NULL,
    price DECIMAL(28,10) NOT NULL, fee DECIMAL(28,8) NOT NULL DEFAULT 0,
    slippage DECIMAL(28,8) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_quant_paper_fill_order FOREIGN KEY(order_id) REFERENCES quant_paper_order(id)
);
