-- Test-only snapshot of the current Flyway schema.

DROP TABLE IF EXISTS `quant_v2_experiment_run_attempt`;

DROP TABLE IF EXISTS `quant_v2_experiment_run`;

DROP TABLE IF EXISTS `quant_v2_experiment`;

DROP TABLE IF EXISTS `quant_v2_research_snapshot`;

DROP TABLE IF EXISTS `quant_v2_paper_event`;

DROP TABLE IF EXISTS `quant_v2_deployment`;

DROP TABLE IF EXISTS `quant_v2_task`;

DROP TABLE IF EXISTS `quant_v2_version`;

DROP TABLE IF EXISTS `quant_v2_object`;

DROP TABLE IF EXISTS `investment_index_display_order`;

DROP TABLE IF EXISTS `investment_index_watchlist`;

DROP TABLE IF EXISTS `quant_benchmark_snapshot`;

DROP TABLE IF EXISTS `benchmark_profile`;

DROP TABLE IF EXISTS `investment_data_job`;

DROP TABLE IF EXISTS `investment_data_quality_issue`;

DROP TABLE IF EXISTS `investment_data_quality_snapshot`;

DROP TABLE IF EXISTS `investment_analysis_snapshot`;

DROP TABLE IF EXISTS `investment_horizon_setting`;

DROP TABLE IF EXISTS `investment_horizon_profile`;

DROP TABLE IF EXISTS `wealth_baseline`;

DROP TABLE IF EXISTS `investment_asset`;

DROP TABLE IF EXISTS `daily_exchange_rate`;

DROP TABLE IF EXISTS `investment_plan`;

DROP TABLE IF EXISTS `investment_sync_batch`;

DROP TABLE IF EXISTS `investment_import_batch`;

DROP TABLE IF EXISTS `product_daily_quote`;

DROP TABLE IF EXISTS `investment_position`;

DROP TABLE IF EXISTS `investment_cash_ledger`;

DROP TABLE IF EXISTS `investment_cash_balance`;

DROP TABLE IF EXISTS `investment_transaction`;

DROP TABLE IF EXISTS `investment_account`;

DROP TABLE IF EXISTS `investment_product`;

DROP TABLE IF EXISTS `agent_schedule_run`;

DROP TABLE IF EXISTS `agent_schedule`;

DROP TABLE IF EXISTS `analysis_record`;

DROP TABLE IF EXISTS `bill_candidate_transaction`;

DROP TABLE IF EXISTS `bill_import_record`;

DROP TABLE IF EXISTS `budget_alert`;

DROP TABLE IF EXISTS `budget`;

DROP TABLE IF EXISTS `pending_action`;

DROP TABLE IF EXISTS `chat_message`;

DROP TABLE IF EXISTS `chat_conversation`;

DROP TABLE IF EXISTS `expense_category`;

DROP TABLE IF EXISTS `transaction`;

DROP TABLE IF EXISTS `agent_context_summary`;

DROP TABLE IF EXISTS `agent_reflection`;

DROP TABLE IF EXISTS `agent_run_step`;

DROP TABLE IF EXISTS `agent_run`;

DROP TABLE IF EXISTS `skill_invocation_record`;

DROP TABLE IF EXISTS `agent_skill`;

DROP TABLE IF EXISTS `agent_memory`;

DROP TABLE IF EXISTS `financial_profile`;

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `username` VARCHAR(50) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `nickname` VARCHAR(50) NULL,
    `email` VARCHAR(100) NULL,
    `avatar` VARCHAR(255) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX user_uk_username ON `user` (username);

CREATE INDEX user_idx_created_at ON `user` (created_at);

CREATE TABLE `financial_profile` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `life_stage` VARCHAR(50) NULL,
    `monthly_income` DECIMAL(12,2) NOT NULL DEFAULT 0,
    `fixed_expense` DECIMAL(12,2) NOT NULL DEFAULT 0,
    `risk_preference` VARCHAR(30) NULL,
    `savings_goal_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
    `savings_goal_deadline` VARCHAR(7) NULL,
    `monthly_budget_goal` DECIMAL(12,2) NOT NULL DEFAULT 0,
    `notes` VARCHAR(500) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_financial_profile_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX financial_profile_uk_profile_user ON `financial_profile` (user_id);

CREATE TABLE `agent_memory` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `memory_type` VARCHAR(50) NOT NULL,
    `memory_key` VARCHAR(100) NOT NULL,
    `memory_value` CLOB NOT NULL,
    `confidence` DOUBLE NOT NULL DEFAULT 1,
    `source_query` VARCHAR(500) NULL,
    `disabled` TINYINT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_memory_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX agent_memory_uk_agent_memory_key ON `agent_memory` (user_id, memory_type, memory_key);

CREATE INDEX agent_memory_idx_agent_memory_user ON `agent_memory` (user_id, disabled, deleted);

CREATE TABLE `agent_skill` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `skill_key` VARCHAR(120) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `description` VARCHAR(500) NULL,
    `version` VARCHAR(50) NULL,
    `author` VARCHAR(120) NULL,
    `category` VARCHAR(80) NULL,
    `risk_level` VARCHAR(50) NULL,
    `input_schema` VARCHAR(500) NULL,
    `trigger_text` VARCHAR(500) NULL,
    `instruction_text` CLOB NULL,
    `bound_tools` VARCHAR(500) NULL,
    `source_type` VARCHAR(50) NOT NULL,
    `source_uri` VARCHAR(500) NOT NULL,
    `source_version` VARCHAR(100) NULL,
    `enabled` TINYINT NOT NULL DEFAULT 1,
    `built_in` TINYINT NOT NULL DEFAULT 0,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_skill_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX agent_skill_uk_agent_skill_source ON `agent_skill` (user_id, source_type, source_uri, skill_key);

CREATE INDEX agent_skill_idx_agent_skill_user ON `agent_skill` (user_id, enabled, deleted);

CREATE TABLE `skill_invocation_record` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `trace_id` VARCHAR(64) NULL,
    `skill_name` VARCHAR(100) NOT NULL,
    `category` VARCHAR(50) NULL,
    `source_type` VARCHAR(50) NULL,
    `risk_level` VARCHAR(50) NULL,
    `input` CLOB NULL,
    `success` TINYINT NOT NULL DEFAULT 0,
    `blocked` TINYINT NOT NULL DEFAULT 0,
    `duration_ms` BIGINT NULL,
    `summary` VARCHAR(500) NULL,
    `raw_result` CLOB NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_skill_invocation_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX skill_invocation_record_idx_skill_trace ON `skill_invocation_record` (trace_id);

CREATE INDEX skill_invocation_record_idx_skill_user ON `skill_invocation_record` (user_id, skill_name);

CREATE TABLE `agent_run` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `trace_id` VARCHAR(64) NOT NULL,
    `query` CLOB NOT NULL,
    `final_answer` CLOB NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
    `started_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `finished_at` TIMESTAMP NULL,
    `duration_ms` BIGINT NULL,
    `error_message` VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_run_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX agent_run_uk_agent_run_trace ON `agent_run` (trace_id);

CREATE INDEX agent_run_idx_agent_run_user ON `agent_run` (user_id, started_at);

CREATE TABLE `agent_run_step` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `trace_id` VARCHAR(64) NOT NULL,
    `step_number` INT NOT NULL,
    `summary` VARCHAR(500) NULL,
    `tool_name` VARCHAR(100) NULL,
    `input` CLOB NULL,
    `success` TINYINT NULL,
    `observation_summary` VARCHAR(500) NULL,
    `error_message` VARCHAR(500) NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
    `started_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `finished_at` TIMESTAMP NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_run_step_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX agent_run_step_uk_agent_run_step ON `agent_run_step` (trace_id, step_number);

CREATE INDEX agent_run_step_idx_agent_run_step_user ON `agent_run_step` (user_id, trace_id);

CREATE TABLE `agent_reflection` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `trace_id` VARCHAR(64) NOT NULL,
    `suggestion_type` VARCHAR(50) NOT NULL,
    `title` VARCHAR(120) NOT NULL,
    `summary` VARCHAR(500) NOT NULL,
    `payload` CLOB NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_reflection_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX agent_reflection_idx_agent_reflection_user ON `agent_reflection` (user_id, status, deleted);

CREATE INDEX agent_reflection_idx_agent_reflection_trace ON `agent_reflection` (trace_id);

CREATE TABLE `agent_context_summary` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `conversation_id` BIGINT NULL,
    `trace_id` VARCHAR(64) NULL,
    `scope` VARCHAR(50) NOT NULL DEFAULT 'CONVERSATION',
    `summary` CLOB NOT NULL,
    `source_refs` CLOB NULL,
    `source_hash` VARCHAR(64) NULL,
    `covered_from_message_id` BIGINT NULL,
    `covered_until_message_id` BIGINT NULL,
    `original_tokens` INT NOT NULL DEFAULT 0,
    `compressed_tokens` INT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_context_summary_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX agent_context_summary_idx_context_summary_conversation ON `agent_context_summary` (user_id, conversation_id, scope, deleted, updated_at);

CREATE INDEX agent_context_summary_idx_context_summary_source ON `agent_context_summary` (user_id, scope, source_hash, deleted);

CREATE INDEX agent_context_summary_idx_context_summary_covered ON `agent_context_summary` (user_id, covered_until_message_id, deleted);

CREATE INDEX agent_context_summary_idx_context_summary_user ON `agent_context_summary` (user_id, deleted, updated_at);

CREATE INDEX agent_context_summary_idx_context_summary_trace ON `agent_context_summary` (trace_id);

CREATE TABLE `transaction` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `amount` DECIMAL(12,2) NOT NULL,
    `type` VARCHAR(10) NOT NULL DEFAULT 'EXPENSE',
    `category` VARCHAR(50) NOT NULL,
    `description` VARCHAR(500) NULL,
    `transaction_date` DATE NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_transaction_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX transaction_idx_user_id ON `transaction` (user_id);

CREATE INDEX transaction_idx_user_date ON `transaction` (user_id, transaction_date);

CREATE INDEX transaction_idx_category ON `transaction` (category);

CREATE TABLE `expense_category` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL DEFAULT 0,
    `name` VARCHAR(50) NOT NULL,
    `icon` VARCHAR(50) NULL,
    `benchmark_min` INT NULL,
    `benchmark_max` INT NULL,
    `benchmark_label` VARCHAR(100) NULL,
    `sort_order` INT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX expense_category_uk_user_category ON `expense_category` (user_id, name);

CREATE INDEX expense_category_idx_user_sort ON `expense_category` (user_id, sort_order);

CREATE TABLE `chat_conversation` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `title` VARCHAR(80) NOT NULL DEFAULT '新对话',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_chat_conversation_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX chat_conversation_idx_chat_conversation_user ON `chat_conversation` (user_id, deleted, updated_at);

CREATE TABLE `chat_message` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `role` VARCHAR(20) NOT NULL,
    `content` CLOB NOT NULL,
    `trace_id` VARCHAR(64) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `conversation_id` BIGINT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX chat_message_idx_chat_conversation ON `chat_message` (conversation_id);

CREATE INDEX chat_message_idx_chat_trace ON `chat_message` (trace_id);

CREATE INDEX chat_message_idx_user_id ON `chat_message` (user_id);

CREATE INDEX chat_message_idx_created_at ON `chat_message` (created_at);

CREATE TABLE `pending_action` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `action_type` VARCHAR(50) NOT NULL,
    `title` VARCHAR(100) NOT NULL,
    `summary` VARCHAR(500) NOT NULL,
    `payload` CLOB NOT NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_pending_action_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX pending_action_idx_pending_user_status ON `pending_action` (user_id, status);

CREATE TABLE `budget` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `month` VARCHAR(7) NOT NULL,
    `budget_amount` DECIMAL(12,2) NOT NULL,
    `alert_threshold` INT NOT NULL DEFAULT 80,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_budget_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX budget_uk_user_category_month ON `budget` (user_id, category, `month`);

CREATE INDEX budget_idx_user_month ON `budget` (user_id, `month`);

CREATE TABLE `budget_alert` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `month` VARCHAR(7) NOT NULL,
    `alert_type` VARCHAR(20) NOT NULL,
    `severity` VARCHAR(10) NOT NULL DEFAULT 'INFO',
    `spent_amount` DECIMAL(12,2) NOT NULL,
    `budget_amount` DECIMAL(12,2) NOT NULL,
    `usage_percent` DECIMAL(5,1) NOT NULL,
    `message` VARCHAR(500) NOT NULL,
    `is_read` TINYINT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_alert_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX budget_alert_idx_user_read ON `budget_alert` (user_id, is_read);

CREATE INDEX budget_alert_idx_user_month ON `budget_alert` (user_id, `month`);

CREATE TABLE `bill_import_record` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `original_filename` VARCHAR(255) NULL,
    `file_path` VARCHAR(500) NOT NULL,
    `bill_type` VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
    `confidence` DECIMAL(5,4) NOT NULL DEFAULT 0,
    `ocr_text` CLOB NULL,
    `warnings` CLOB NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_bill_import_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX bill_import_record_idx_bill_user ON `bill_import_record` (user_id);

CREATE INDEX bill_import_record_idx_bill_status ON `bill_import_record` (user_id, status);

CREATE TABLE `bill_candidate_transaction` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `bill_import_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    `amount` DECIMAL(12,2) NOT NULL,
    `type` VARCHAR(10) NOT NULL DEFAULT 'EXPENSE',
    `category` VARCHAR(50) NOT NULL DEFAULT '其他',
    `description` VARCHAR(500) NULL,
    `transaction_date` DATE NOT NULL,
    `confidence` DECIMAL(5,4) NOT NULL DEFAULT 0,
    `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    `transaction_id` BIGINT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_candidate_bill FOREIGN KEY (bill_import_id) REFERENCES `bill_import_record` (id) ON DELETE CASCADE,
    CONSTRAINT fk_candidate_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX bill_candidate_transaction_idx_candidate_bill ON `bill_candidate_transaction` (bill_import_id);

CREATE INDEX bill_candidate_transaction_idx_candidate_user ON `bill_candidate_transaction` (user_id, status);

CREATE TABLE `analysis_record` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `trace_id` VARCHAR(64) NULL,
    `query` CLOB NOT NULL,
    `plan` CLOB NULL,
    `steps_result` CLOB NULL,
    `final_answer` CLOB NULL,
    `score` INT NULL,
    `feedback` VARCHAR(500) NULL,
    `tokens_used` INT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_analysis_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX analysis_record_idx_user_id ON `analysis_record` (user_id);

CREATE INDEX analysis_record_idx_created_at ON `analysis_record` (created_at);

CREATE INDEX analysis_record_idx_analysis_trace ON `analysis_record` (trace_id);

CREATE TABLE `agent_schedule` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `trace_id` VARCHAR(64) NULL,
    `name` VARCHAR(200) NOT NULL,
    `description` VARCHAR(500) NULL,
    `cron_expression` VARCHAR(100) NOT NULL,
    `timezone` VARCHAR(50) NOT NULL DEFAULT 'Asia/Shanghai',
    `task_query` CLOB NOT NULL,
    `enabled` TINYINT NOT NULL DEFAULT 1,
    `last_run_at` TIMESTAMP NULL,
    `next_run_at` TIMESTAMP NULL,
    `lock_until` TIMESTAMP NULL,
    `run_count` INT NOT NULL DEFAULT 0,
    `consecutive_failures` INT NOT NULL DEFAULT 0,
    `last_status` VARCHAR(20) NULL,
    `last_answer` CLOB NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_schedule_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX agent_schedule_idx_agent_schedule_user ON `agent_schedule` (user_id, enabled, deleted);

CREATE INDEX agent_schedule_idx_agent_schedule_next_run ON `agent_schedule` (enabled, next_run_at);

CREATE INDEX agent_schedule_idx_agent_schedule_lock ON `agent_schedule` (enabled, lock_until);

CREATE TABLE `agent_schedule_run` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `schedule_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    `trace_id` VARCHAR(64) NULL,
    `status` VARCHAR(20) NOT NULL,
    `answer` CLOB NULL,
    `error_message` CLOB NULL,
    `started_at` TIMESTAMP NOT NULL,
    `finished_at` TIMESTAMP NOT NULL,
    `duration_ms` BIGINT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_schedule_run_schedule FOREIGN KEY (schedule_id) REFERENCES `agent_schedule` (id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_schedule_run_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE
);

CREATE INDEX agent_schedule_run_idx_agent_schedule_run_schedule ON `agent_schedule_run` (schedule_id, created_at);

CREATE INDEX agent_schedule_run_idx_agent_schedule_run_user ON `agent_schedule_run` (user_id, created_at);

CREATE INDEX agent_schedule_run_idx_agent_schedule_run_trace ON `agent_schedule_run` (trace_id);

CREATE TABLE `investment_product` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `product_type` VARCHAR(30) NOT NULL,
    `market` VARCHAR(30) NOT NULL,
    `code` VARCHAR(40) NOT NULL,
    `name` VARCHAR(160) NOT NULL,
    `currency` VARCHAR(3) NOT NULL DEFAULT 'CNY',
    `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `inception_date` DATE NULL,
    `history_start_date` DATE NULL,
    `history_end_date` DATE NULL,
    `history_coverage_complete` BOOLEAN NOT NULL DEFAULT FALSE,
    `fund_type_raw` VARCHAR(80) NULL,
    `fund_category` VARCHAR(40) NULL,
    `classification_source` VARCHAR(60) NULL,
    `classification_version` VARCHAR(80) NULL,
    `classified_at` TIMESTAMP NULL,
    PRIMARY KEY (id)
);

CREATE INDEX investment_product_idx_investment_product_fund_category ON `investment_product` (product_type, fund_category);

CREATE UNIQUE INDEX investment_product_uk_investment_product ON `investment_product` (product_type, market, code);

CREATE TABLE `investment_account` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `account_name` VARCHAR(120) NOT NULL,
    `account_type` VARCHAR(30) NOT NULL,
    `base_currency` VARCHAR(3) NOT NULL DEFAULT 'CNY',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE INDEX investment_account_idx_investment_account_user ON `investment_account` (user_id, deleted);

CREATE TABLE `investment_transaction` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `account_id` BIGINT NOT NULL,
    `product_id` BIGINT NULL,
    `event_type` VARCHAR(30) NOT NULL,
    `trade_date` DATE NOT NULL,
    `settlement_date` DATE NULL,
    `currency` VARCHAR(3) NOT NULL,
    `quantity` DECIMAL(28,10) NULL,
    `price` DECIMAL(28,10) NULL,
    `amount` DECIMAL(28,8) NULL,
    `fee` DECIMAL(28,8) NOT NULL DEFAULT 0,
    `factor` DECIMAL(28,10) NULL,
    `source` VARCHAR(30) NOT NULL DEFAULT 'MANUAL',
    `external_ref` VARCHAR(120) NULL,
    `reversal_transaction_id` BIGINT NULL,
    `note` VARCHAR(500) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX investment_transaction_uk_investment_transaction_ref ON `investment_transaction` (user_id, source, external_ref);

CREATE INDEX investment_transaction_idx_investment_transaction_account ON `investment_transaction` (user_id, account_id, trade_date);

CREATE INDEX investment_transaction_idx_investment_transaction_product ON `investment_transaction` (account_id, product_id, trade_date);

CREATE TABLE `investment_cash_balance` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `account_id` BIGINT NOT NULL,
    `currency` VARCHAR(3) NOT NULL,
    `balance` DECIMAL(28,8) NOT NULL DEFAULT 0,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX investment_cash_balance_uk_investment_cash_balance ON `investment_cash_balance` (account_id, currency);

CREATE INDEX investment_cash_balance_idx_investment_cash_user ON `investment_cash_balance` (user_id, account_id);

CREATE TABLE `investment_cash_ledger` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `account_id` BIGINT NOT NULL,
    `transaction_id` BIGINT NOT NULL,
    `currency` VARCHAR(3) NOT NULL,
    `event_type` VARCHAR(30) NOT NULL,
    `amount` DECIMAL(28,8) NOT NULL,
    `external_flow` TINYINT NOT NULL DEFAULT 0,
    `occurred_on` DATE NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX investment_cash_ledger_uk_investment_cash_transaction ON `investment_cash_ledger` (transaction_id);

CREATE INDEX investment_cash_ledger_idx_investment_cash_ledger_account ON `investment_cash_ledger` (user_id, account_id, occurred_on);

CREATE TABLE `investment_position` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `account_id` BIGINT NOT NULL,
    `product_id` BIGINT NOT NULL,
    `quantity` DECIMAL(28,10) NOT NULL DEFAULT 0,
    `cost_amount` DECIMAL(28,8) NOT NULL DEFAULT 0,
    `average_cost` DECIMAL(28,10) NOT NULL DEFAULT 0,
    `realized_pnl` DECIMAL(28,8) NOT NULL DEFAULT 0,
    `latest_price` DECIMAL(28,10) NULL,
    `market_value_cny` DECIMAL(28,8) NULL,
    `unrealized_pnl_cny` DECIMAL(28,8) NULL,
    `data_date` DATE NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX investment_position_uk_investment_position ON `investment_position` (account_id, product_id);

CREATE INDEX investment_position_idx_investment_position_user ON `investment_position` (user_id, account_id);

CREATE TABLE `product_daily_quote` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `product_id` BIGINT NOT NULL,
    `trade_date` DATE NOT NULL,
    `open_price` DECIMAL(28,10) NULL,
    `high_price` DECIMAL(28,10) NULL,
    `low_price` DECIMAL(28,10) NULL,
    `close_price` DECIMAL(28,10) NOT NULL,
    `volume` DECIMAL(28,8) NULL,
    `adjust_type` VARCHAR(20) NOT NULL DEFAULT 'NONE',
    `source` VARCHAR(40) NOT NULL,
    `adapter_version` VARCHAR(40) NULL,
    `synced_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `previous_close` DECIMAL(28,10) NULL,
    `change_amount` DECIMAL(28,10) NULL,
    `change_percent` DECIMAL(18,8) NULL,
    `amount` DECIMAL(28,8) NULL,
    `turnover_rate` DECIMAL(18,8) NULL,
    `volume_ratio` DECIMAL(18,8) NULL,
    `amplitude` DECIMAL(18,8) NULL,
    `total_return_index` DECIMAL(28,10) NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX product_daily_quote_uk_product_daily_quote ON `product_daily_quote` (product_id, trade_date, adjust_type);

CREATE TABLE `investment_import_batch` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `original_filename` VARCHAR(255) NOT NULL,
    `status` VARCHAR(30) NOT NULL,
    `payload` CLOB NOT NULL,
    `row_count` INT NOT NULL DEFAULT 0,
    `error_count` INT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX investment_import_batch_idx_investment_import_user ON `investment_import_batch` (user_id, status);

CREATE TABLE `investment_sync_batch` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `job_type` VARCHAR(40) NOT NULL,
    `provider` VARCHAR(40) NULL,
    `status` VARCHAR(30) NOT NULL,
    `rows_success` INT NOT NULL DEFAULT 0,
    `rows_failed` INT NOT NULL DEFAULT 0,
    `error_message` VARCHAR(500) NULL,
    `started_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `finished_at` TIMESTAMP NULL,
    PRIMARY KEY (id)
);

CREATE INDEX investment_sync_batch_idx_investment_sync_user ON `investment_sync_batch` (user_id, started_at);

CREATE TABLE `investment_plan` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `account_id` BIGINT NOT NULL,
    `product_id` BIGINT NOT NULL,
    `amount` DECIMAL(28,8) NOT NULL,
    `currency` VARCHAR(3) NOT NULL,
    `frequency` VARCHAR(20) NOT NULL,
    `execution_day` INT NOT NULL,
    `next_execution_date` DATE NOT NULL,
    `last_execution_date` DATE NULL,
    `last_execution_amount` DECIMAL(28,8) NULL,
    `last_execution_price` DECIMAL(28,10) NULL,
    `execution_count` INT NOT NULL DEFAULT 0,
    `last_execution_status` VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    `last_execution_message` VARCHAR(500) NULL,
    `enabled` TINYINT NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX investment_plan_idx_investment_plan_due ON `investment_plan` (enabled, next_execution_date);

CREATE INDEX investment_plan_idx_investment_plan_user ON `investment_plan` (user_id, enabled, next_execution_date);

CREATE TABLE `daily_exchange_rate` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `base_currency` VARCHAR(3) NOT NULL,
    `quote_currency` VARCHAR(3) NOT NULL,
    `rate_date` DATE NOT NULL,
    `rate` DECIMAL(28,10) NOT NULL,
    `source` VARCHAR(40) NOT NULL,
    `adapter_version` VARCHAR(40),
    `synced_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX daily_exchange_rate_uk_daily_exchange_rate ON `daily_exchange_rate` (base_currency, quote_currency, rate_date);

CREATE TABLE `investment_asset` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `user_id` BIGINT NOT NULL,
    `account_id` BIGINT NOT NULL,
    `product_id` BIGINT NOT NULL,
    `quantity` DECIMAL(28,10),
    `average_cost` DECIMAL(28,10),
    `note` VARCHAR(500),
    `current_transaction_id` BIGINT,
    `sync_status` VARCHAR(30) NOT NULL DEFAULT 'NOT_SYNCED',
    `sync_error` VARCHAR(500),
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE INDEX investment_asset_idx_investment_asset_user ON `investment_asset` (user_id, deleted, updated_at);

CREATE INDEX investment_asset_idx_investment_asset_product ON `investment_asset` (user_id, product_id, deleted);

CREATE TABLE `wealth_baseline` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `entered_total_assets` DECIMAL(28,8) NOT NULL,
    `baseline_non_investment_balance` DECIMAL(28,8) NOT NULL,
    `baseline_at` TIMESTAMP NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX wealth_baseline_uk_wealth_baseline_user ON `wealth_baseline` (user_id);

CREATE TABLE `investment_horizon_profile` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `scope_type` VARCHAR(16) NOT NULL,
    `asset_id` BIGINT,
    `version` INT NOT NULL,
    `template_version` VARCHAR(64) NOT NULL,
    `source` VARCHAR(24) NOT NULL,
    `active` BOOLEAN NOT NULL DEFAULT 1,
    `effective_from` TIMESTAMP NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX investment_horizon_profile_idx_horizon_profile_resolution ON `investment_horizon_profile` (user_id, scope_type, asset_id, active, version);

CREATE TABLE `investment_horizon_setting` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `profile_id` BIGINT NOT NULL,
    `horizon_code` VARCHAR(32) NOT NULL,
    `display_name` VARCHAR(50) NOT NULL,
    `sort_order` INT NOT NULL,
    `min_holding_days` INT NOT NULL,
    `max_holding_days` INT NOT NULL,
    `target_holding_days` INT NOT NULL,
    `is_primary` BOOLEAN NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_horizon_setting_profile FOREIGN KEY (profile_id) REFERENCES `investment_horizon_profile` (id)
);

CREATE UNIQUE INDEX investment_horizon_setting_uk_horizon_setting_profile_code ON `investment_horizon_setting` (profile_id, horizon_code);

CREATE INDEX investment_horizon_setting_idx_horizon_setting_profile ON `investment_horizon_setting` (profile_id, sort_order);

CREATE TABLE `investment_analysis_snapshot` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `asset_id` BIGINT NOT NULL,
    `rule_version` VARCHAR(40) NOT NULL,
    `preference_hash` VARCHAR(64) NOT NULL,
    `horizon_profile_version` VARCHAR(255),
    `horizon_config_json` CLOB,
    `dataset_version` VARCHAR(64),
    `quality_rule_set_version` VARCHAR(80),
    `strategy_version` VARCHAR(80),
    `analysis_cache_key` VARCHAR(64),
    `quality_status` VARCHAR(16),
    `historical_cache` BOOLEAN NOT NULL DEFAULT 0,
    `signal_hash` VARCHAR(64),
    `quote_date` DATE,
    `technical_json` CLOB,
    `fundamental_json` CLOB,
    `fund_json` CLOB,
    `backtest_json` CLOB,
    `source_status_json` CLOB,
    `ai_explanation` CLOB,
    `analysis_status` VARCHAR(30) NOT NULL DEFAULT 'READY',
    `analyzed_at` TIMESTAMP NOT NULL,
    `ai_updated_at` TIMESTAMP,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX investment_analysis_snapshot_uk_analysis_snapshot_user_asset_rule ON `investment_analysis_snapshot` (user_id, asset_id, rule_version);

CREATE INDEX investment_analysis_snapshot_idx_analysis_cache_key ON `investment_analysis_snapshot` (user_id, asset_id, analysis_cache_key);

CREATE INDEX investment_analysis_snapshot_idx_analysis_dataset_version ON `investment_analysis_snapshot` (dataset_version);

CREATE TABLE `investment_data_quality_snapshot` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `dataset_version` VARCHAR(64) NOT NULL,
    `product_type` VARCHAR(30) NOT NULL,
    `code` VARCHAR(40) NOT NULL,
    `market` VARCHAR(20) NOT NULL,
    `frequency` VARCHAR(16) NOT NULL,
    `adjust_type` VARCHAR(16) NOT NULL,
    `provider` VARCHAR(80) NOT NULL,
    `adapter_version` VARCHAR(80) NOT NULL,
    `quality_config_version` VARCHAR(80) NOT NULL,
    `quality_rule_set_version` VARCHAR(80) NOT NULL,
    `quality_status` VARCHAR(16) NOT NULL,
    `decision` VARCHAR(16) NOT NULL,
    `enforcement_mode` VARCHAR(16) NOT NULL,
    `requested_start_date` DATE NOT NULL,
    `requested_end_date` DATE NOT NULL,
    `sample_start_date` DATE NOT NULL,
    `sample_end_date` DATE NOT NULL,
    `fetched_at` TIMESTAMP NOT NULL,
    `evaluated_at` TIMESTAMP NOT NULL,
    `manifest_json` CLOB NOT NULL,
    `report_json` CLOB NOT NULL,
    `secondary_dataset_versions_json` CLOB,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX investment_data_quality_snapshot_uk_data_quality_dataset_rule ON `investment_data_quality_snapshot` (dataset_version, quality_config_version);

CREATE INDEX investment_data_quality_snapshot_idx_data_quality_dataset_version ON `investment_data_quality_snapshot` (dataset_version);

CREATE INDEX investment_data_quality_snapshot_idx_data_quality_product_range ON `investment_data_quality_snapshot` (product_type, code, market, requested_start_date, requested_end_date);

CREATE INDEX investment_data_quality_snapshot_idx_data_quality_status ON `investment_data_quality_snapshot` (quality_status, evaluated_at);

CREATE TABLE `investment_data_quality_issue` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `quality_snapshot_id` BIGINT NOT NULL,
    `sequence_no` INT NOT NULL,
    `rule_code` VARCHAR(80) NOT NULL,
    `severity` VARCHAR(16) NOT NULL,
    `outcome` VARCHAR(24) NOT NULL,
    `message` CLOB NOT NULL,
    `observed_json` CLOB,
    `expected_json` CLOB,
    `affected_dates_json` CLOB,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_data_quality_issue_snapshot FOREIGN KEY (quality_snapshot_id) REFERENCES `investment_data_quality_snapshot` (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX investment_data_quality_issue_uk_data_quality_issue_order ON `investment_data_quality_issue` (quality_snapshot_id, sequence_no);

CREATE INDEX investment_data_quality_issue_idx_data_quality_issue_rule ON `investment_data_quality_issue` (rule_code, severity);

CREATE TABLE `investment_data_job` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `asset_id` BIGINT NOT NULL,
    `product_id` BIGINT NOT NULL,
    `job_type` VARCHAR(30) NOT NULL,
    `status` VARCHAR(20) NOT NULL,
    `force_refresh` TINYINT NOT NULL DEFAULT 0,
    `record_count` INT NOT NULL DEFAULT 0,
    `attempt_count` INT NOT NULL DEFAULT 0,
    `next_retry_at` TIMESTAMP,
    `lease_until` TIMESTAMP,
    `lease_token` VARCHAR(36),
    `error_message` VARCHAR(1000),
    `started_at` TIMESTAMP,
    `finished_at` TIMESTAMP,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `requested_start_date` DATE NULL,
    `sample_start_date` DATE NULL,
    `sample_end_date` DATE NULL,
    `coverage_complete` TINYINT NULL,
    `dataset_version` VARCHAR(128) NULL
);

CREATE UNIQUE INDEX investment_data_job_uk_investment_data_job_asset_type ON `investment_data_job` (asset_id, job_type);

CREATE INDEX investment_data_job_idx_investment_data_job_pending ON `investment_data_job` (status, next_retry_at, created_at);

CREATE TABLE `benchmark_profile` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `product_type` VARCHAR(30) NOT NULL,
    `product_code` VARCHAR(40),
    `model_family` VARCHAR(40) NOT NULL,
    `benchmark_code` VARCHAR(80) NOT NULL,
    `display_name` VARCHAR(255) NOT NULL,
    `composition_json` CLOB NOT NULL,
    `currency` VARCHAR(10) NOT NULL,
    `fx_rule` VARCHAR(40),
    `source_uri` VARCHAR(1000) NOT NULL,
    `source_version` VARCHAR(80) NOT NULL,
    `effective_from` DATE NOT NULL,
    `effective_to` DATE,
    `active` BOOLEAN NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX benchmark_profile_uk_benchmark_profile_version ON `benchmark_profile` (product_type, product_code, effective_from);

CREATE INDEX benchmark_profile_idx_benchmark_profile_lookup ON `benchmark_profile` (product_type, product_code, active, effective_from);

CREATE TABLE `quant_benchmark_snapshot` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `snapshot_version` CHAR(64) NOT NULL,
    `benchmark_profile_id` BIGINT NOT NULL,
    `benchmark_code` VARCHAR(80) NOT NULL,
    `source_uri` VARCHAR(1000) NOT NULL,
    `source_version` VARCHAR(80) NOT NULL,
    `provider` VARCHAR(40),
    `adapter_version` VARCHAR(40),
    `currency` VARCHAR(10) NOT NULL,
    `fx_rule` VARCHAR(40),
    `effective_from` DATE NOT NULL,
    `effective_to` DATE,
    `sample_start_date` DATE NOT NULL,
    `sample_end_date` DATE NOT NULL,
    `fetched_at` TIMESTAMP NOT NULL,
    `records_json` CLOB NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX quant_benchmark_snapshot_uk_quant_benchmark_snapshot_version ON `quant_benchmark_snapshot` (snapshot_version);

CREATE INDEX quant_benchmark_snapshot_idx_quant_benchmark_snapshot_lookup ON `quant_benchmark_snapshot` (benchmark_profile_id, sample_start_date, sample_end_date, fetched_at);

CREATE TABLE `investment_index_watchlist` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `index_code` VARCHAR(64) NOT NULL,
    `display_name` VARCHAR(120) NOT NULL,
    `market` VARCHAR(20) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0
);

CREATE INDEX investment_index_watchlist_idx_investment_index_watchlist_user ON `investment_index_watchlist` (user_id, deleted, created_at);

CREATE INDEX investment_index_watchlist_idx_investment_index_watchlist_code ON `investment_index_watchlist` (user_id, index_code, deleted);

CREATE TABLE `investment_index_display_order` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `index_code` VARCHAR(64) NOT NULL,
    `sort_order` INT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX investment_index_display_order_uk_investment_index_display_order ON `investment_index_display_order` (user_id, index_code);

CREATE INDEX investment_index_display_order_idx_investment_index_display_order_user ON `investment_index_display_order` (user_id, sort_order);

CREATE TABLE `quant_v2_object` (
    `id` VARCHAR(36) PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `kind` VARCHAR(20) NOT NULL,
    `name` VARCHAR(160) NOT NULL,
    `status` VARCHAR(24) NOT NULL,
    `revision` INT NOT NULL,
    `payload` CLOB NOT NULL,
    `created_at` VARCHAR(40) NOT NULL,
    `updated_at` VARCHAR(40) NOT NULL
);

CREATE INDEX quant_v2_object_idx_qv2_object_owner ON `quant_v2_object` (user_id,kind,status);

CREATE TABLE `quant_v2_version` (
    `id` VARCHAR(36) PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `object_id` VARCHAR(36) NOT NULL,
    `version` INT NOT NULL,
    `payload` CLOB NOT NULL,
    `created_at` VARCHAR(40) NOT NULL,
    UNIQUE(object_id,version)
);

CREATE INDEX quant_v2_version_idx_qv2_version_owner ON `quant_v2_version` (user_id,object_id);

CREATE TABLE `quant_v2_task` (
    `id` VARCHAR(36) PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `kind` VARCHAR(20) NOT NULL,
    `name` VARCHAR(160) NOT NULL,
    `status` VARCHAR(24) NOT NULL,
    `stage` VARCHAR(40) NOT NULL,
    `strategy_id` VARCHAR(36),
    `strategy_version_id` VARCHAR(36),
    `universe_id` VARCHAR(36),
    `request_json` CLOB NOT NULL,
    `result_json` CLOB,
    `error_code` VARCHAR(80),
    `error_message` CLOB,
    `claim_token` VARCHAR(36),
    `lease_until` BIGINT,
    `created_at` VARCHAR(40) NOT NULL,
    `updated_at` VARCHAR(40) NOT NULL
);

CREATE INDEX quant_v2_task_idx_qv2_task_owner ON `quant_v2_task` (user_id,kind,created_at);

CREATE INDEX quant_v2_task_idx_qv2_task_claim ON `quant_v2_task` (status,lease_until);

CREATE TABLE `quant_v2_deployment` (
    `id` VARCHAR(36) PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `name` VARCHAR(160) NOT NULL,
    `backtest_id` VARCHAR(36) NOT NULL,
    `strategy_id` VARCHAR(36) NOT NULL,
    `universe_id` VARCHAR(36) NOT NULL,
    `status` VARCHAR(24) NOT NULL,
    `revision` INT NOT NULL,
    `request_json` CLOB NOT NULL,
    `result_json` CLOB,
    `error_code` VARCHAR(80),
    `error_message` CLOB,
    `claim_token` VARCHAR(36),
    `lease_until` BIGINT,
    `next_run_at` BIGINT NOT NULL,
    `created_at` VARCHAR(40) NOT NULL,
    `updated_at` VARCHAR(40) NOT NULL
);

CREATE INDEX quant_v2_deployment_idx_qv2_deployment_owner ON `quant_v2_deployment` (user_id,status);

CREATE TABLE `quant_v2_paper_event` (
    `id` VARCHAR(36) PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `deployment_id` VARCHAR(36) NOT NULL,
    `event_key` VARCHAR(160) NOT NULL,
    `kind` VARCHAR(24) NOT NULL,
    `payload` CLOB NOT NULL,
    `created_at` VARCHAR(40) NOT NULL,
    UNIQUE(deployment_id,event_key)
);

CREATE INDEX quant_v2_paper_event_idx_qv2_event_owner ON `quant_v2_paper_event` (user_id,deployment_id);

CREATE TABLE `quant_v2_research_snapshot` (
    `id` VARCHAR(36) PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `format_version` VARCHAR(40) NOT NULL,
    `content_hash` CHAR(64) NOT NULL,
    `compression` VARCHAR(16) NOT NULL,
    `payload_blob` BLOB NOT NULL,
    `metadata_json` CLOB NOT NULL,
    `uncompressed_bytes` BIGINT NOT NULL,
    `compressed_bytes` BIGINT NOT NULL,
    `created_at` VARCHAR(40) NOT NULL
);

CREATE UNIQUE INDEX quant_v2_research_snapshot_uk_qv2_research_snapshot_content ON `quant_v2_research_snapshot` (user_id,format_version,content_hash);

CREATE TABLE `quant_v2_experiment` (
    `id` VARCHAR(36) PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `name` VARCHAR(160) NOT NULL,
    `status` VARCHAR(24) NOT NULL,
    `source_backtest_id` VARCHAR(36) NOT NULL,
    `strategy_id` VARCHAR(36) NOT NULL,
    `strategy_version_id` VARCHAR(36) NOT NULL,
    `universe_id` VARCHAR(36) NOT NULL,
    `universe_version_id` VARCHAR(36) NOT NULL,
    `factor_id` VARCHAR(36),
    `factor_version_id` VARCHAR(36),
    `snapshot_id` VARCHAR(36) NOT NULL,
    `model_ref` VARCHAR(160),
    `model_task_id` VARCHAR(36),
    `variable_definition_json` CLOB NOT NULL,
    `baseline_values_json` CLOB NOT NULL,
    `candidate_values_json` CLOB NOT NULL,
    `base_request_json` CLOB NOT NULL,
    `source_context_json` CLOB NOT NULL,
    `environment_json` CLOB NOT NULL,
    `candidate_rule_version` VARCHAR(64) NOT NULL,
    `stability_algorithm_version` VARCHAR(64) NOT NULL,
    `invariant_hash` CHAR(64) NOT NULL,
    `summary_json` CLOB,
    `request_key` VARCHAR(80),
    `request_hash` CHAR(64),
    `revision` INT NOT NULL,
    `created_at` VARCHAR(40) NOT NULL,
    `updated_at` VARCHAR(40) NOT NULL,
    `completed_at` VARCHAR(40),
    `cancelled_at` VARCHAR(40)
);

CREATE INDEX quant_v2_experiment_idx_qv2_experiment_owner ON `quant_v2_experiment` (user_id,status,created_at);

CREATE INDEX quant_v2_experiment_idx_qv2_experiment_strategy ON `quant_v2_experiment` (user_id,strategy_id,strategy_version_id);

CREATE UNIQUE INDEX quant_v2_experiment_uk_qv2_experiment_request ON `quant_v2_experiment` (user_id,request_key);

CREATE TABLE `quant_v2_experiment_run` (
    `id` VARCHAR(36) PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `experiment_id` VARCHAR(36) NOT NULL,
    `ordinal` INT NOT NULL,
    `variable_values_json` CLOB NOT NULL,
    `value_hash` CHAR(64) NOT NULL,
    `baseline` BOOLEAN NOT NULL,
    `active_attempt_id` VARCHAR(36),
    `created_at` VARCHAR(40) NOT NULL
);

CREATE INDEX quant_v2_experiment_run_idx_qv2_experiment_run_owner ON `quant_v2_experiment_run` (user_id,experiment_id);

CREATE UNIQUE INDEX quant_v2_experiment_run_uk_qv2_experiment_run_value ON `quant_v2_experiment_run` (experiment_id,value_hash);

CREATE UNIQUE INDEX quant_v2_experiment_run_uk_qv2_experiment_run_ordinal ON `quant_v2_experiment_run` (experiment_id,ordinal);

CREATE TABLE `quant_v2_experiment_run_attempt` (
    `id` VARCHAR(36) PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `run_id` VARCHAR(36) NOT NULL,
    `attempt_no` INT NOT NULL,
    `reason` VARCHAR(32) NOT NULL,
    `task_id` VARCHAR(36) NOT NULL,
    `created_at` VARCHAR(40) NOT NULL
);

CREATE INDEX quant_v2_experiment_run_attempt_idx_qv2_experiment_attempt_owner ON `quant_v2_experiment_run_attempt` (user_id,run_id);

CREATE UNIQUE INDEX quant_v2_experiment_run_attempt_uk_qv2_experiment_attempt_number ON `quant_v2_experiment_run_attempt` (run_id,attempt_no);

CREATE UNIQUE INDEX quant_v2_experiment_run_attempt_uk_qv2_experiment_attempt_task ON `quant_v2_experiment_run_attempt` (task_id);
