DROP TABLE IF EXISTS expense_category;
DROP TABLE IF EXISTS chat_message;
DROP TABLE IF EXISTS pending_action;
DROP TABLE IF EXISTS bill_candidate_transaction;
DROP TABLE IF EXISTS bill_import_record;
DROP TABLE IF EXISTS transaction;
DROP TABLE IF EXISTS financial_profile;
DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    nickname   VARCHAR(50),
    email      VARCHAR(100),
    avatar     VARCHAR(255),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted    TINYINT      NOT NULL DEFAULT 0
);

CREATE TABLE financial_profile
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT        NOT NULL UNIQUE,
    life_stage            VARCHAR(50),
    monthly_income        DECIMAL(12,2) NOT NULL DEFAULT 0,
    fixed_expense         DECIMAL(12,2) NOT NULL DEFAULT 0,
    risk_preference       VARCHAR(30),
    savings_goal_amount   DECIMAL(12,2) NOT NULL DEFAULT 0,
    savings_goal_deadline VARCHAR(7),
    monthly_budget_goal   DECIMAL(12,2) NOT NULL DEFAULT 0,
    notes                 VARCHAR(500),
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_financial_profile_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL,
    amount           DECIMAL(12,2) NOT NULL,
    type             VARCHAR(10)   NOT NULL DEFAULT 'EXPENSE',
    category         VARCHAR(50)   NOT NULL,
    description      VARCHAR(500),
    transaction_date DATE          NOT NULL,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          TINYINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_transaction_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE expense_category
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL DEFAULT 0,
    name            VARCHAR(50)  NOT NULL,
    icon            VARCHAR(50),
    benchmark_min   INT,
    benchmark_max   INT,
    benchmark_label VARCHAR(100),
    sort_order      INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_user_category UNIQUE (user_id, name)
);

CREATE TABLE chat_message
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    role       VARCHAR(20) NOT NULL,
    content    TEXT        NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE pending_action
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    action_type VARCHAR(50)  NOT NULL,
    title       VARCHAR(100) NOT NULL,
    summary     VARCHAR(500) NOT NULL,
    payload     TEXT         NOT NULL,
    status      VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pending_action_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE bill_import_record
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    original_filename VARCHAR(255),
    file_path         VARCHAR(500) NOT NULL,
    bill_type         VARCHAR(50)  NOT NULL DEFAULT 'UNKNOWN',
    confidence        DECIMAL(5,4) NOT NULL DEFAULT 0,
    ocr_text          TEXT,
    warnings          TEXT,
    status            VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           TINYINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_bill_import_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE bill_candidate_transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_import_id   BIGINT        NOT NULL,
    user_id          BIGINT        NOT NULL,
    amount           DECIMAL(12,2) NOT NULL,
    type             VARCHAR(10)   NOT NULL DEFAULT 'EXPENSE',
    category         VARCHAR(50)   NOT NULL DEFAULT '其他',
    description      VARCHAR(500),
    transaction_date DATE          NOT NULL,
    confidence       DECIMAL(5,4)  NOT NULL DEFAULT 0,
    status           VARCHAR(30)   NOT NULL DEFAULT 'PENDING',
    transaction_id   BIGINT,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          TINYINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_candidate_bill FOREIGN KEY (bill_import_id) REFERENCES bill_import_record (id) ON DELETE CASCADE,
    CONSTRAINT fk_candidate_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);
