import request from './request'

export const getInvestmentOverviewAPI = () => request.get('/investment/overview')
export const listInvestmentAccountsAPI = () => request.get('/investment/accounts')
export const createInvestmentAccountAPI = data => request.post('/investment/accounts', data)
export const searchInvestmentProductsAPI = params => request.get('/investment/products', { params })
export const listInvestmentPositionsAPI = params => request.get('/investment/positions', { params })
export const listInvestmentTransactionsAPI = params => request.get('/investment/transactions', { params })
export const createInvestmentTransactionAPI = data => request.post('/investment/transactions', data)
export const reverseInvestmentTransactionAPI = (id, note) => request.post(`/investment/transactions/${id}/reverse`, { note })
export const previewInvestmentImportAPI = file => {
  const data = new FormData()
  data.append('file', file)
  return request.post('/investment/imports/preview', data, { headers: { 'Content-Type': 'multipart/form-data' } })
}
export const commitInvestmentImportAPI = data => request.post('/investment/imports/commit', data)
export const getInvestmentAnalysisAPI = () => request.get('/investment/analysis')
export const getInvestmentRecommendationsAPI = () => request.get('/investment/recommendations')
export const requestInvestmentSyncAPI = () => request.post('/investment/sync')
export const listInvestmentPlansAPI = () => request.get('/investment/plans')
export const createInvestmentPlanAPI = data => request.post('/investment/plans', data)
export const setInvestmentPlanEnabledAPI = (id, enabled) => request.post(`/investment/plans/${id}/enabled`, { enabled })
export const resolveInvestmentAssetAPI = data => request.post('/investment/assets/resolve', data)
export const createInvestmentAssetAPI = data => request.post('/investment/assets', data)
export const listInvestmentAssetsAPI = () => request.get('/investment/assets')
export const getInvestmentAssetAPI = id => request.get(`/investment/assets/${id}`)
export const updateInvestmentAssetAPI = (id, data) => request.put(`/investment/assets/${id}`, data)
export const deleteInvestmentAssetAPI = id => request.delete(`/investment/assets/${id}`)
export const syncInvestmentAssetAPI = id => request.post(`/investment/assets/${id}/sync`)
export const getInvestmentAssetDetailAPI = id => request.get(`/investment/assets/${id}/detail`, { timeout: 60000 })
export const getInvestmentAssetAnalysisAPI = id => request.get(`/investment/assets/${id}/analysis`, { timeout: 60000 })
export const getInvestmentHorizonProfileAPI = () => request.get('/investment/horizon-profile')
export const updateInvestmentHorizonProfileAPI = data => request.put('/investment/horizon-profile', data)
export const updateInvestmentAssetHorizonOverrideAPI = (id, data) => request.put(`/investment/assets/${id}/analysis-preference`, data, { timeout: 60000 })
export const clearInvestmentAssetHorizonOverrideAPI = id => request.delete(`/investment/assets/${id}/analysis-preference`, { timeout: 60000 })
export const refreshInvestmentAssetAnalysisAPI = id => request.post(`/investment/assets/${id}/analysis/refresh`, null, { timeout: 60000 })
